name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: my-website-azure    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './publish'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.x.x'           # set this to the dot net version to use

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ./MyWebsite.sln
        
      - name: Build
        run: dotnet build MyWebsite./MyWebsite.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish MyWebsite/MVC/MVC.csproj--configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
